# NumPy Indexing and Selection

In [1]:
import numpy as np

In [4]:
#creating a simple array
arr=np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[6:10]

array([6, 7, 8, 9])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0:4]=100

In [14]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [15]:
arr=np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [18]:
bool_arr = arr>4

In [19]:
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [20]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
x = 5
arr[arr>x]

array([ 6,  7,  8,  9, 10])